//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RobotC.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RobotCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IRobotCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] RobotCParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] RobotCParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotCParser.variableExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableExpr([NotNull] RobotCParser.VariableExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotCParser.variableExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableExpr([NotNull] RobotCParser.VariableExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RobotCParser.assignmentStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStmt([NotNull] RobotCParser.AssignmentStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RobotCParser.assignmentStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStmt([NotNull] RobotCParser.AssignmentStmtContext context);
}
